/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedOperationsIndexRouteImport } from './routes/_authenticated/operations/index'
import { Route as AuthenticatedOperationsIdRouteImport } from './routes/_authenticated/operations/$id'
import { Route as AuthenticatedSampleChildrenIndexRouteImport } from './routes/_authenticated/sample-children/index'
import { Route as AuthenticatedSampleChildrenNewRouteImport } from './routes/_authenticated/sample-children/new'
import { Route as AuthenticatedSamplesIndexRouteImport } from './routes/_authenticated/samples/index'
import { Route as AuthenticatedSamplesNewRouteImport } from './routes/_authenticated/samples/new'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSampleChildrenIdIndexRouteImport } from './routes/_authenticated/sample-children/$id/index'
import { Route as AuthenticatedSampleChildrenIdAuditHistoryRouteImport } from './routes/_authenticated/sample-children/$id/audit-history'
import { Route as AuthenticatedSampleChildrenIdEditRouteImport } from './routes/_authenticated/sample-children/$id/edit'
import { Route as AuthenticatedSamplesIdIndexRouteImport } from './routes/_authenticated/samples/$id/index'
import { Route as AuthenticatedSamplesIdAuditHistoryRouteImport } from './routes/_authenticated/samples/$id/audit-history'
import { Route as AuthenticatedSamplesIdEditRouteImport } from './routes/_authenticated/samples/$id/edit'
import { Route as AuthenticatedUsersIdIndexRouteImport } from './routes/_authenticated/users/$id/index'
import { Route as AuthenticatedUsersIdAuditHistoryRouteImport } from './routes/_authenticated/users/$id/audit-history'
import { Route as AuthenticatedUsersIdEditRouteImport } from './routes/_authenticated/users/$id/edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationsIndexRoute =
  AuthenticatedOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationsIdRoute =
  AuthenticatedOperationsIdRouteImport.update({
    id: '/operations/$id',
    path: '/operations/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSampleChildrenIndexRoute =
  AuthenticatedSampleChildrenIndexRouteImport.update({
    id: '/sample-children/',
    path: '/sample-children/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSampleChildrenNewRoute =
  AuthenticatedSampleChildrenNewRouteImport.update({
    id: '/sample-children/new',
    path: '/sample-children/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplesIndexRoute =
  AuthenticatedSamplesIndexRouteImport.update({
    id: '/samples/',
    path: '/samples/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplesNewRoute = AuthenticatedSamplesNewRouteImport.update({
  id: '/samples/new',
  path: '/samples/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSampleChildrenIdIndexRoute =
  AuthenticatedSampleChildrenIdIndexRouteImport.update({
    id: '/sample-children/$id/',
    path: '/sample-children/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSampleChildrenIdAuditHistoryRoute =
  AuthenticatedSampleChildrenIdAuditHistoryRouteImport.update({
    id: '/sample-children/$id/audit-history',
    path: '/sample-children/$id/audit-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSampleChildrenIdEditRoute =
  AuthenticatedSampleChildrenIdEditRouteImport.update({
    id: '/sample-children/$id/edit',
    path: '/sample-children/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplesIdIndexRoute =
  AuthenticatedSamplesIdIndexRouteImport.update({
    id: '/samples/$id/',
    path: '/samples/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplesIdAuditHistoryRoute =
  AuthenticatedSamplesIdAuditHistoryRouteImport.update({
    id: '/samples/$id/audit-history',
    path: '/samples/$id/audit-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSamplesIdEditRoute =
  AuthenticatedSamplesIdEditRouteImport.update({
    id: '/samples/$id/edit',
    path: '/samples/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersIdIndexRoute =
  AuthenticatedUsersIdIndexRouteImport.update({
    id: '/users/$id/',
    path: '/users/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersIdAuditHistoryRoute =
  AuthenticatedUsersIdAuditHistoryRouteImport.update({
    id: '/users/$id/audit-history',
    path: '/users/$id/audit-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersIdEditRoute =
  AuthenticatedUsersIdEditRouteImport.update({
    id: '/users/$id/edit',
    path: '/users/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/callback': typeof CallbackRoute
  '/operations/$id': typeof AuthenticatedOperationsIdRoute
  '/sample-children/new': typeof AuthenticatedSampleChildrenNewRoute
  '/samples/new': typeof AuthenticatedSamplesNewRoute
  '/operations/': typeof AuthenticatedOperationsIndexRoute
  '/sample-children/': typeof AuthenticatedSampleChildrenIndexRoute
  '/samples/': typeof AuthenticatedSamplesIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/sample-children/$id/audit-history': typeof AuthenticatedSampleChildrenIdAuditHistoryRoute
  '/sample-children/$id/edit': typeof AuthenticatedSampleChildrenIdEditRoute
  '/samples/$id/audit-history': typeof AuthenticatedSamplesIdAuditHistoryRoute
  '/samples/$id/edit': typeof AuthenticatedSamplesIdEditRoute
  '/users/$id/audit-history': typeof AuthenticatedUsersIdAuditHistoryRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/sample-children/$id/': typeof AuthenticatedSampleChildrenIdIndexRoute
  '/samples/$id/': typeof AuthenticatedSamplesIdIndexRoute
  '/users/$id/': typeof AuthenticatedUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/operations/$id': typeof AuthenticatedOperationsIdRoute
  '/sample-children/new': typeof AuthenticatedSampleChildrenNewRoute
  '/samples/new': typeof AuthenticatedSamplesNewRoute
  '/operations': typeof AuthenticatedOperationsIndexRoute
  '/sample-children': typeof AuthenticatedSampleChildrenIndexRoute
  '/samples': typeof AuthenticatedSamplesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/sample-children/$id/audit-history': typeof AuthenticatedSampleChildrenIdAuditHistoryRoute
  '/sample-children/$id/edit': typeof AuthenticatedSampleChildrenIdEditRoute
  '/samples/$id/audit-history': typeof AuthenticatedSamplesIdAuditHistoryRoute
  '/samples/$id/edit': typeof AuthenticatedSamplesIdEditRoute
  '/users/$id/audit-history': typeof AuthenticatedUsersIdAuditHistoryRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/sample-children/$id': typeof AuthenticatedSampleChildrenIdIndexRoute
  '/samples/$id': typeof AuthenticatedSamplesIdIndexRoute
  '/users/$id': typeof AuthenticatedUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/operations/$id': typeof AuthenticatedOperationsIdRoute
  '/_authenticated/sample-children/new': typeof AuthenticatedSampleChildrenNewRoute
  '/_authenticated/samples/new': typeof AuthenticatedSamplesNewRoute
  '/_authenticated/operations/': typeof AuthenticatedOperationsIndexRoute
  '/_authenticated/sample-children/': typeof AuthenticatedSampleChildrenIndexRoute
  '/_authenticated/samples/': typeof AuthenticatedSamplesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/sample-children/$id/audit-history': typeof AuthenticatedSampleChildrenIdAuditHistoryRoute
  '/_authenticated/sample-children/$id/edit': typeof AuthenticatedSampleChildrenIdEditRoute
  '/_authenticated/samples/$id/audit-history': typeof AuthenticatedSamplesIdAuditHistoryRoute
  '/_authenticated/samples/$id/edit': typeof AuthenticatedSamplesIdEditRoute
  '/_authenticated/users/$id/audit-history': typeof AuthenticatedUsersIdAuditHistoryRoute
  '/_authenticated/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/_authenticated/sample-children/$id/': typeof AuthenticatedSampleChildrenIdIndexRoute
  '/_authenticated/samples/$id/': typeof AuthenticatedSamplesIdIndexRoute
  '/_authenticated/users/$id/': typeof AuthenticatedUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/operations/$id'
    | '/sample-children/new'
    | '/samples/new'
    | '/operations/'
    | '/sample-children/'
    | '/samples/'
    | '/users/'
    | '/sample-children/$id/audit-history'
    | '/sample-children/$id/edit'
    | '/samples/$id/audit-history'
    | '/samples/$id/edit'
    | '/users/$id/audit-history'
    | '/users/$id/edit'
    | '/sample-children/$id/'
    | '/samples/$id/'
    | '/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/'
    | '/operations/$id'
    | '/sample-children/new'
    | '/samples/new'
    | '/operations'
    | '/sample-children'
    | '/samples'
    | '/users'
    | '/sample-children/$id/audit-history'
    | '/sample-children/$id/edit'
    | '/samples/$id/audit-history'
    | '/samples/$id/edit'
    | '/users/$id/audit-history'
    | '/users/$id/edit'
    | '/sample-children/$id'
    | '/samples/$id'
    | '/users/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/'
    | '/_authenticated/operations/$id'
    | '/_authenticated/sample-children/new'
    | '/_authenticated/samples/new'
    | '/_authenticated/operations/'
    | '/_authenticated/sample-children/'
    | '/_authenticated/samples/'
    | '/_authenticated/users/'
    | '/_authenticated/sample-children/$id/audit-history'
    | '/_authenticated/sample-children/$id/edit'
    | '/_authenticated/samples/$id/audit-history'
    | '/_authenticated/samples/$id/edit'
    | '/_authenticated/users/$id/audit-history'
    | '/_authenticated/users/$id/edit'
    | '/_authenticated/sample-children/$id/'
    | '/_authenticated/samples/$id/'
    | '/_authenticated/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations/': {
      id: '/_authenticated/operations/'
      path: '/operations'
      fullPath: '/operations/'
      preLoaderRoute: typeof AuthenticatedOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations/$id': {
      id: '/_authenticated/operations/$id'
      path: '/operations/$id'
      fullPath: '/operations/$id'
      preLoaderRoute: typeof AuthenticatedOperationsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample-children/': {
      id: '/_authenticated/sample-children/'
      path: '/sample-children'
      fullPath: '/sample-children/'
      preLoaderRoute: typeof AuthenticatedSampleChildrenIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample-children/new': {
      id: '/_authenticated/sample-children/new'
      path: '/sample-children/new'
      fullPath: '/sample-children/new'
      preLoaderRoute: typeof AuthenticatedSampleChildrenNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples/': {
      id: '/_authenticated/samples/'
      path: '/samples'
      fullPath: '/samples/'
      preLoaderRoute: typeof AuthenticatedSamplesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples/new': {
      id: '/_authenticated/samples/new'
      path: '/samples/new'
      fullPath: '/samples/new'
      preLoaderRoute: typeof AuthenticatedSamplesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample-children/$id/': {
      id: '/_authenticated/sample-children/$id/'
      path: '/sample-children/$id'
      fullPath: '/sample-children/$id/'
      preLoaderRoute: typeof AuthenticatedSampleChildrenIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample-children/$id/audit-history': {
      id: '/_authenticated/sample-children/$id/audit-history'
      path: '/sample-children/$id/audit-history'
      fullPath: '/sample-children/$id/audit-history'
      preLoaderRoute: typeof AuthenticatedSampleChildrenIdAuditHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sample-children/$id/edit': {
      id: '/_authenticated/sample-children/$id/edit'
      path: '/sample-children/$id/edit'
      fullPath: '/sample-children/$id/edit'
      preLoaderRoute: typeof AuthenticatedSampleChildrenIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples/$id/': {
      id: '/_authenticated/samples/$id/'
      path: '/samples/$id'
      fullPath: '/samples/$id/'
      preLoaderRoute: typeof AuthenticatedSamplesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples/$id/audit-history': {
      id: '/_authenticated/samples/$id/audit-history'
      path: '/samples/$id/audit-history'
      fullPath: '/samples/$id/audit-history'
      preLoaderRoute: typeof AuthenticatedSamplesIdAuditHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/samples/$id/edit': {
      id: '/_authenticated/samples/$id/edit'
      path: '/samples/$id/edit'
      fullPath: '/samples/$id/edit'
      preLoaderRoute: typeof AuthenticatedSamplesIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$id/': {
      id: '/_authenticated/users/$id/'
      path: '/users/$id'
      fullPath: '/users/$id/'
      preLoaderRoute: typeof AuthenticatedUsersIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$id/audit-history': {
      id: '/_authenticated/users/$id/audit-history'
      path: '/users/$id/audit-history'
      fullPath: '/users/$id/audit-history'
      preLoaderRoute: typeof AuthenticatedUsersIdAuditHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$id/edit': {
      id: '/_authenticated/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof AuthenticatedUsersIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOperationsIdRoute: typeof AuthenticatedOperationsIdRoute
  AuthenticatedSampleChildrenNewRoute: typeof AuthenticatedSampleChildrenNewRoute
  AuthenticatedSamplesNewRoute: typeof AuthenticatedSamplesNewRoute
  AuthenticatedOperationsIndexRoute: typeof AuthenticatedOperationsIndexRoute
  AuthenticatedSampleChildrenIndexRoute: typeof AuthenticatedSampleChildrenIndexRoute
  AuthenticatedSamplesIndexRoute: typeof AuthenticatedSamplesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedSampleChildrenIdAuditHistoryRoute: typeof AuthenticatedSampleChildrenIdAuditHistoryRoute
  AuthenticatedSampleChildrenIdEditRoute: typeof AuthenticatedSampleChildrenIdEditRoute
  AuthenticatedSamplesIdAuditHistoryRoute: typeof AuthenticatedSamplesIdAuditHistoryRoute
  AuthenticatedSamplesIdEditRoute: typeof AuthenticatedSamplesIdEditRoute
  AuthenticatedUsersIdAuditHistoryRoute: typeof AuthenticatedUsersIdAuditHistoryRoute
  AuthenticatedUsersIdEditRoute: typeof AuthenticatedUsersIdEditRoute
  AuthenticatedSampleChildrenIdIndexRoute: typeof AuthenticatedSampleChildrenIdIndexRoute
  AuthenticatedSamplesIdIndexRoute: typeof AuthenticatedSamplesIdIndexRoute
  AuthenticatedUsersIdIndexRoute: typeof AuthenticatedUsersIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOperationsIdRoute: AuthenticatedOperationsIdRoute,
  AuthenticatedSampleChildrenNewRoute: AuthenticatedSampleChildrenNewRoute,
  AuthenticatedSamplesNewRoute: AuthenticatedSamplesNewRoute,
  AuthenticatedOperationsIndexRoute: AuthenticatedOperationsIndexRoute,
  AuthenticatedSampleChildrenIndexRoute: AuthenticatedSampleChildrenIndexRoute,
  AuthenticatedSamplesIndexRoute: AuthenticatedSamplesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedSampleChildrenIdAuditHistoryRoute:
    AuthenticatedSampleChildrenIdAuditHistoryRoute,
  AuthenticatedSampleChildrenIdEditRoute:
    AuthenticatedSampleChildrenIdEditRoute,
  AuthenticatedSamplesIdAuditHistoryRoute:
    AuthenticatedSamplesIdAuditHistoryRoute,
  AuthenticatedSamplesIdEditRoute: AuthenticatedSamplesIdEditRoute,
  AuthenticatedUsersIdAuditHistoryRoute: AuthenticatedUsersIdAuditHistoryRoute,
  AuthenticatedUsersIdEditRoute: AuthenticatedUsersIdEditRoute,
  AuthenticatedSampleChildrenIdIndexRoute:
    AuthenticatedSampleChildrenIdIndexRoute,
  AuthenticatedSamplesIdIndexRoute: AuthenticatedSamplesIdIndexRoute,
  AuthenticatedUsersIdIndexRoute: AuthenticatedUsersIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
